### ISSUE TITLE
No bed leveling?

### ISSUE THREAD

**Issue by fingon** [luke-saunders/TevoFlash-Cura#1]
https://github.com/luke-saunders/TevoFlash-Cura/blob/e693813a9bf0feae8df66248f3aab8e4f5a054f2/tevo_flash_definition/resources/definitions/tevo_flash.def.json#L75

The definition is missing bed leveling initialization:
```
G29 ; Auto bed level
```
which I inserted after G28, and printing worked much better for me at least. (My bed isn't quite 100% level, but with bed leveling it seems to work well enough).

**Comment by luke-saunders** [comment]
Hi Markus,

Thanks. I'll add it to the definition.

Cheers,
Luke
